version: "3.9"

services:
  chatgpt_bot:
    build:
      context: .
      dockerfile: dockerfile
    image: chatgpt_bot
    container_name: chatgpt_bot
    volumes:
      - ./logs:/app/logs
    restart: always